### PR TITLE
Use a cache key involving filename and mtime when possible.

### LINKED ISSUE #98: Investigate double compile.
I’ve been working on a PR to use mtime in the cache name (related to #95) and running into test fails that don't happen if I use the `content`.

For example take `test/name.js`.
There are 2 cache reads (both with the same mtime but different contents).

The first time is the original file:
```js
var path = require("path");

export var id = module.id,
  name = path.basename(__filename);

export function foo() {
  return "foo";
}
```

The second time is the modified contents:
```js
(function (exports, require, module, __filename, __dirname) { module.export({id:function(){return id},name:function(){return name},foo:function(){return foo}});var path = require("path");

var id = module.id,
  name = path.basename(__filename);

function foo() {
  return "foo";
}

});
```

The file itself isn't changes which is why the mtime is unchanged but the content passed to `compile` is. I think there’s misdirection going on.

Between the two cache checks it looks like `Module.load` and `Module._compile` are only called once so maybe it’s coming from another place.

### PR DESCRIPTION
**Pull request by benjamn**
The `vm.*` wrappers registered by [`repl/index.js`](https://github.com/benjamn/reify/blob/master/repl/index.js) still just hash the contents, so those cache entries should no longer collide with the ones used by `Module.prototype._compile`.

Part of #90.
Closes #98.

### CODE REVIEW

File: node/caching-compiler.js [hunk 1]
```diff
@@ -103,16 +111,18 @@ function readFileOrNull(filename) {
...
-function getCacheFilename(content, reify) {
-  const hash = createHash("sha1")
-    .update(reifyVersion).update("\0")
-    .update(content).update("\0");
-
-  if (reify) {
-    hash.update(JSON.stringify(reify));
+function getCacheFilename() {
+  const args = [];
+  const argc = arguments.length;
```
Comment (jdalton) [inline node/caching-compiler.js]: other places you use `xyzCount` so prolly consistency with that instead of `argc` maybe `argsCount`.

File: node/caching-compiler.js [hunk 2]
```diff
@@ -103,16 +111,18 @@ function readFileOrNull(filename) {
...
+  for (let i = 0; i < argc; ++i) {
+    args.push(arguments[i]);
```
Comment (jdalton) [inline node/caching-compiler.js]: Since this is a straight assignment you can do:
```js
const argsCount = arguments.length;
const args = new Array(argsCount)

for (let i = 0; i < argsCount; ++i) {
  args[i] = arguments[i];
}
```

File: node/compile-hook.js [hunk 3]
```diff
@@ -11,10 +12,31 @@ if (! _compile.reified) {
...
+    options.cacheKey = {
+      source: "Module.prototype._compile",
+      filename: filename,
+      mtime: mtime
+    };
+  }
+
+  return options;
+}
+
```
Comment (jdalton) [inline node/compile-hook.js]: I think there's already a `statOrNull` helper somewhere maybe a `node/util.js` would be handy.

File: node/compile-hook.js [hunk 4]
```diff
@@ -11,10 +12,31 @@ if (! _compile.reified) {
...
+function getOptions(filename) {
+  const options = { filename: filename };
+  const mtime = mtimeOrNull(filename);
+
+  if (mtime !== null) {
+    options.cacheKey = {
+      source: "Module.prototype._compile",
+      filename: filename,
+      mtime: mtime
+    };
```
Comment (jdalton) [inline node/compile-hook.js]: JSON stringifying a date will produce a string.
```js
JSON.stringify({ 'a': new Date })
// => '{"a":"2017-03-28T21:36:01.892Z"}'
```
You could have it be a timestamp which I think is a bit better
```js
mtime: mtime.getTime()
```

File: node/compile-hook.js [hunk 5]
```diff
@@ -11,10 +12,31 @@ if (! _compile.reified) {
...
   }).reified = _compile;
 }
+
+function getOptions(filename) {
+  const options = { filename: filename };
+  const mtime = mtimeOrNull(filename);
+
+  if (mtime !== null) {
+    options.cacheKey = {
+      source: "Module.prototype._compile",
```
Comment (jdalton) [inline node/compile-hook.js]: What's the `source` bit do?

File: node/caching-compiler.js [hunk 6]
```diff
@@ -17,27 +17,32 @@ const reifyVersion = require("../package.json")
...
 
-exports.compile = (content, filename) => {
-  if (filename === "repl") {
+exports.compile = (content, options) => {
+  options = options || Object.create(null);
+
+  if (options.filename === "repl") {
     // Treat the REPL as if there was no filename.
-    filename = null;
+    options.filename = null;
```
Comment (jdalton) [inline node/caching-compiler.js]: We shouldn't mutate the `options` object. It can be avoided by using `options = Object.assign(Object.create(null), options)` or by referencing the options as one off vars.

File: node/caching-compiler.js [hunk 7]
```diff
@@ -17,27 +17,32 @@ const reifyVersion = require("../package.json")
...
-    ? readWithCacheAndFilename(pkgInfo, content, filename)
-    : readWithCache(pkgInfo, content);
+  return options.filename
+    ? readWithCacheAndFilename(pkgInfo, content, options)
+    : readWithCache(pkgInfo, content, options);
 };
 
-function readWithCacheAndFilename(pkgInfo, content, filename) {
+function readWithCacheAndFilename(pkgInfo, content, options) {
   try {
```
Comment (jdalton) [inline node/caching-compiler.js]: When I was working with this for the PR I didn't really dig the names of the methods. I was like `readWithCacheAnd....` then I saw it was also writing the file and compiling. I dig the separation to allow try-catch for just the case where a filename is known but didn't bikeshed a better name yet.

File: node/caching-compiler.js [hunk 8]
```diff
@@ -103,16 +111,18 @@ function readFileOrNull(filename) {
...
+  const argc = arguments.length;
+  for (let i = 0; i < argc; ++i) {
+    args.push(arguments[i]);
   }
 
-  return hash.digest("hex") + ".js";
+  return createHash("sha1")
+    .update(reifyVersion)
+    .update("\0")
+    .update(JSON.stringify(args))
```
Comment (jdalton) [inline node/caching-compiler.js]: There are some valid JS `content` values which are not valid inside string literals (like one or two bizarro encodings). That makes me a little worried about using `JSON.stringify` here. It also seems super heavy since we know the arg count is 2 and type detection for one of cacheKey or content is pretty straight forward.

Comment (jdalton) [inline node/caching-compiler.js]: Maybe just `JSON.stringify` on `reify` when it exists since when it does it will be a valid JSON object.

File: node/caching-compiler.js [hunk 9]
```diff
@@ -103,16 +111,18 @@ function readFileOrNull(filename) {
...
-    hash.update(JSON.stringify(reify));
+function getCacheFilename() {
+  const args = [];
+  const argc = arguments.length;
+  for (let i = 0; i < argc; ++i) {
+    args.push(arguments[i]);
   }
 
-  return hash.digest("hex") + ".js";
+  return createHash("sha1")
```
Comment (jdalton) [inline node/caching-compiler.js]: If it helps with flow you can create the values to add to `createHash("sha1")` as an array and then do
`createHash("sha1").update(values.join("\0")).digest("hex")`

File: node/compile-hook.js (hunk 5 above)
Comment (benjamn) [inline node/compile-hook.js]: Just a salt to distinguish this call site from any other places where we might call `cachingCompiler.compile`.

File: node/caching-compiler.js (hunk 6 above)
Comment (benjamn) [inline node/caching-compiler.js]: Agreed.

**Comment by jdalton** [comment]
Rock!
